/* MI-4A1000M */

#define BOARD_PID		"MI-4A1000M"
#define BOARD_NAME		"MI-4A1000M"
#define BOARD_DESC		"MI 4A1000M Wireless Router"
#define BOARD_VENDOR_NAME	"xiaomi Technology"
#define BOARD_VENDOR_URL	"http://www.miwifi.com/"
#define BOARD_MODEL_URL		"http://www.miwifi.com/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET	18
#define BOARD_GPIO_BTN_WPS	12
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#undef  BOARD_GPIO_LED_POWER
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	6
#undef BOARD_GPIO_LED_USB
#undef BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	0
#define BOARD_USB_PORT_SWAP	0
